apiVersion: v1
kind: Namespace
metadata:
  name: k8s-labs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: probes-demo
  namespace: k8s-labs
  labels:
    app: probes-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: probes-demo
  template:
    metadata:
      labels:
        app: probes-demo
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: web
          image: nginxinc/nginx-unprivileged:1.27-alpine
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
---
apiVersion: v1
kind: Service
metadata:
  name: probes-demo
  namespace: k8s-labs
spec:
  selector:
    app: probes-demo
  ports:
    - name: http
      port: 8080
      targetPort: 8080
